modLoader = "javafml"
loaderVersion = "[10,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "itemzoomer"
version = "${version}"
displayName = "Item Zoomer"
authors = "iMeeTake"
description = '''
Zoom in on hovered items in the inventory.
'''
logoFile = "itemzoomer.png"

[[dependencies.itemzoomer]]
modId = "neoforge"
type = "required"
versionRange = "[21.10,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemzoomer]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11]"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemzoomer]]
modId = "architectury"
type = "required"
versionRange = "[19.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.itemzoomer]]
modId = "cloth_config"
type = "required"
versionRange = "[21.11.153,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.itemzoomer]]
modId = "jei"
type = "optional"
versionRange = "[27.0,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.itemzoomer]]
modId = "rei"
type = "optional"
versionRange = "[21.0,)"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "itemzoomer.mixins.json"
