modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "itemzoomer"
version = "${version}"
displayName = "Item Zoomer"
authors = "iMeeTake"
description = '''
Zoom in on hovered items in the inventory.
'''
logoFile = "itemzoomer.png"

[[dependencies.itemzoomer]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemzoomer]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemzoomer]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.itemzoomer]]
modId = "cloth_config"
type = "required"
versionRange = "[15.0.140,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.itemzoomer]]
modId = "jei"
type = "optional"
versionRange = "[19.0,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.itemzoomer]]
modId = "rei"
type = "optional"
versionRange = "[16.0,)"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "itemzoomer.mixins.json"
