modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "itemzoomer"
version = "${version}"
displayName = "Item Zoomer"
authors = "iMeeTake"
description = '''
Zoom in on hovered items in the inventory.
'''
#logoFile = ""

[[dependencies.itemzoomer]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemzoomer]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemzoomer]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
